# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d43ad2c4-988e-4dab-9191-b92c661ef2d3";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/78D4-38EE";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Phân vùng swap 10G (nvme0n1p3). Khai ở ĐÂY thay vì trong module laptop.nix vì
  # nixos-generate-config sẽ tự sinh mục này theo đúng swap đang bật — máy mới làm
  # theo docs/03-Cai-May-Moi.md Bước 7 là swap tự khớp, chỉ còn sửa resume=UUID=.
  swapDevices = [
    {
      device = "/dev/disk/by-uuid/044520bf-eed9-498c-a382-97615c111b1f";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
